### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by Charadon** [awersching/wedder#3]
For some reason I keep getting an error that says "No Internet", I'm putting in a valid api key, and I even put in some coordinates. But it still refuses to do anything

OS: Manjaro

**Comment by awersching** [comment]
Could you please post the debug output using ```wedder -d```?

**Comment by Charadon** [comment]
I won't post the entire debug since it gives away coordinates, but I will post these 2 errors:
`09:30:38 [ERROR] wedder::http - error sending request for url (http://ip-api.com/json/?fields=city,lat,lon): error trying to connect: tcp connect error: Connection refused (os error 111)`

`09:30:38 [WARN] wedder::config::file - No config file found under /home/charadon/.config/wedder/wedder.toml, using defaults
`

Also apologies for not getting back sooner

This error seems to be caused by the fact that I have ip-api.com blacklisted in my /etc/hosts. Any option to disable that IP check?

**Comment by awersching** [comment]
Thanks!
You can disable the IP check by setting the location provider to "Manual" in addition to setting the coordinates. So for example as arguments:
```
wedder --location-provider Manual --lat "63.415245" --lon "10.409906"
```
Sorry if that wasn't documented clearly.

**Comment by Charadon** [comment]
Thanks, and a couple of other things.
1. How do you do negatives when defining coordinates?
2. When you select Fahrenheit as your temperature unit, it still puts a C next to it instead of an F.

**Comment by awersching** [comment]
1. Thanks for the hint, you're right negative coordinates don't work as arguments. I'll fix that. For now you could also set the coordinates in the config file ([take a look at the example](https://github.com/awersching/wedder/blob/master/examples/wedder.toml)), it works there.
2. You have to change the format, the default is ```"<icon>  <temperature>°C"``` so you can use e.g. this instead: 
```
wedder -f "<icon>  <temperature>°F"
```

**Comment by Charadon** [comment]
Oh cool, I didn't notice the config file example, that made configuring this a breeze. Thanks!
