### ISSUE TITLE
Location provider seems dead

### ISSUE THREAD

**Issue by fdw** [awersching/wedder#6]
Hi, wedder looks quite nice, but I can't get it to work, unfortunately. I want automatic localisation, but `http://ip-api.com` cannot be resolved :(

**Comment by awersching** [comment]
Sounds like `http://ip-api.com` may be blacklisted somewhere, is your network using any kind of DNS restrictions?

**Comment by fdw** [comment]
Now it's working again, thanks :)
When I wrote that ticket, it was completely down.

**Comment by fdw** [comment]
At the moment, it's down again for me :(

**Comment by awersching** [comment]
Weird, I've never had problems with IP-API, I'll look into adding another location provider in the future
