### ISSUE TITLE
<precipitation_chance> is not resolved

### ISSUE THREAD

**Issue by fdw** [awersching/wedder#7]
Sorry, me again ;)
`<precipitation_chance>` or `<precipitation` is not resolved. I think the problem is that the response doesn't contain the relevant fields, but I don't know why that is. How can I debug that further?

**Comment by awersching** [comment]
Yes, OpenWeatherMap is unfortunately a bit unpredictable with what kind of fields it sends. If it's currently raining there will usually be precipitation info but if the weather is good the fields are missing.

**Comment by awersching** [comment]
`<precipitation_chance>` and `<precipitation>` are currently only available in the development version, I'll update the stable version in the next couple of days
