### ISSUE TITLE
Idea: Show forecasts

### ISSUE THREAD

**Issue by fdw** [awersching/wedder#8]
Hi, I still like your tool and think about new ways to use it :)

Do you think it would be useful to show some kind of forecasts, like "50% probability for the next four hours"?

**Comment by awersching** [comment]
Yes, I thought about something like that, but decided that it would be out of the scope of this project as I created it specifically for the current weather. Also I'm not sure if forecasts would add too much bloat to the status bar

**Comment by fdw** [comment]
Makes sense, thank you :)
